#!/usr/bin/env ruby

=begin

Installs configuration files in directory by symlinking their current
location to your home directory (~/).

Shamelessly stolen from Chris Lloyd <chris.lloyd@gmail.com>

=end

require 'pathname'

# Colors
{ :green => 32, :grey => 37 }.each do |name, code|
  Kernel.instance_eval { define_method(name) { |str| "\e[#{code}m#{str}\e[0m" } }
end

def abs(path)
  Pathname(path).expand_path
end

def system(cmd)
  puts grey(cmd)
  super(cmd)
end

Dir['*'].
  map { |f| Pathname(f).expand_path }.
  reject { |f| f == Pathname(__FILE__).expand_path }.
  each { |f|
    home = abs "~/.#{f.basename}"
    cmd = "ln -is #{f} #{home}"
    system cmd
  }

puts green('Linked dotfiles')

system 'mkdir ~/misc'
system 'mkdir ~/import'
system 'mkdir ~/backup'
system 'mkdir ~/backup/vim'
system 'mkdir ~/backup/vim/swap'
